# Generated by Django 3.2.13 on 2024-03-26 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20240326_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likepost',
            name='username',
        ),
        migrations.AddField(
            model_name='likepost',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.profile'),
            preserve_default=False,
        ),
    ]
