# Generated by Django 3.2.13 on 2024-03-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20240326_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likepost',
            name='post',
            field=models.CharField(max_length=500),
        ),
    ]
