# Generated by Django 3.2.13 on 2024-03-26 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_likepost_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likepost',
            old_name='post',
            new_name='post_id',
        ),
    ]
