# Generated by Django 3.2.13 on 2024-03-26 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_likepost_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likepost',
            old_name='user',
            new_name='username',
        ),
    ]
